#include "openMVG/cameras/Camera_Pinhole.hpp"
#include "openMVG/cameras/Camera_Pinhole_Radial.hpp"
#include "openMVG/cameras/Camera_Pinhole_Brown.hpp"
#include "openMVG/cameras/Camera_undistort_image.hpp"
#include "openMVG/features/feature.hpp"
#include "openMVG/image/image_io.hpp"
#include "openMVG/sfm/sfm_data.hpp"
#include "openMVG/sfm/sfm_data_colorization.hpp"
#include "openMVG/sfm/sfm_data_io.hpp"

#include "openMVG/system/loggerprogress.hpp"
#include "third_party/cmdLine/cmdLine.h"
#include "third_party/stlplus3/filesystemSimplified/file_system.hpp"

using namespace openMVG;
using namespace openMVG::cameras;
using namespace openMVG::geometry;
using namespace openMVG::image;
using namespace openMVG::sfm;
using namespace openMVG::features;

#ifdef OPENMVG_USE_OPENMP
#include <omp.h>
#endif

#include <cctype>
#include <cstdlib>
#include <iomanip>
#include <ios>
#include <locale>

// Exporting structure in a PLY file
// @note Points are exported in nerf frame. (right handed)
inline bool Save_PLY( const SfM_Data&    sfm_data,
                      const std::string& filename,
                      bool               b_write_in_ascii = false )
{

  const Landmarks&       landmarks = sfm_data.GetLandmarks();
  system::LoggerProgress my_progress_bar( landmarks.size(), "- Exporting model -" );

  // Create the stream and check its status
  std::ofstream stream( filename.c_str(), std::ios::out | std::ios::binary );
  if ( !stream )
    return false;

  bool bOk = false;
  {

    stream << std::fixed << std::setprecision( std::numeric_limits<double>::digits10 + 1 );

    using Vec3uc = Eigen::Matrix<unsigned char, 3, 1>;

    stream << "ply"
           << '\n'
           << "format "
           << ( b_write_in_ascii ? "ascii 1.0" : "binary_little_endian 1.0" )
           << '\n'
           << "comment generated by OpenMVG"
           << '\n'
           << "element vertex "
           // Vertex count: (#landmark + #GCP + #view_with_valid_pose)
           << sfm_data.GetLandmarks().size()
           << '\n'
           << "property double x"
           << '\n'
           << "property double y"
           << '\n'
           << "property double z"
           << '\n'
           << "property uchar red"
           << '\n'
           << "property uchar green"
           << '\n'
           << "property uchar blue"
           << '\n'
           << "end_header" << std::endl;

    // Export structure points as White points (gaussian splatting training process will assign color)
    for ( const auto& iterLandmarks : landmarks )
    {
      if ( b_write_in_ascii )
      {
        stream
            << iterLandmarks.second.X( 0 ) << ' '
            << iterLandmarks.second.X( 2 ) << ' '
            << -iterLandmarks.second.X( 1 ) << ' '
            << "255 255 255\n";
      }
      else
      {
        double data[] = { iterLandmarks.second.X( 0 ), iterLandmarks.second.X( 2 ), -iterLandmarks.second.X( 1 ) };

        stream.write( reinterpret_cast<const char*>( data ), 3 * sizeof( double ) );
        stream.write( reinterpret_cast<const char*>( Vec3uc( 255, 255, 255 ).data() ), sizeof( Vec3uc ) );
      }
      ++my_progress_bar;
    }

    stream.flush();
    bOk = stream.good();
    stream.close();
  }
  return bOk;
}

void ComputeImageMask( Image<RGBColor>& imageIn, const IntrinsicBase* cam, Image<unsigned char>& mask )
{
  // Note: nerf studio only support (1channel) mask images.
  mask = Image<unsigned char>( imageIn.Width(), imageIn.Height() );
  mask.fill( 0 ); // by default ignore all pixels.

  for ( int j = 0; j < imageIn.Height(); ++j )
  {
    for ( int i = 0; i < imageIn.Width(); ++i )
    {
      const Vec2 undisto_pix( i, j );
      // compute coordinates with distortion
      const Vec2 disto_pix = cam->get_d_pixel( undisto_pix );
      // pick pixel if it is in the image domain
      if ( imageIn.Contains( disto_pix( 1 ), disto_pix( 0 ) ) )
      {
        mask( j, i ) = 255;
      }
    }
  }
}

void export_images( const SfM_Data&    sfm_data,
                    const std::string& sOutViewsDirectory )
{
  const Views&           views = sfm_data.GetViews();
  system::LoggerProgress my_progress_bar( sfm_data.GetIntrinsics().size(), "- Exporting images and masks -" );

  const std::string imageDirectory = stlplus::create_filespec( sOutViewsDirectory, "images" );
  const std::string maskDirectory  = stlplus::create_filespec( sOutViewsDirectory, "masks" );

#pragma omp parallel for schedule( dynamic )
  for ( int i = 0; i < static_cast<int>( views.size() ); ++i )
  {
    auto views_it = views.begin();
    std::advance( views_it, i );
    const View* view = views_it->second.get();

    if ( !sfm_data.IsPoseAndIntrinsicDefined( view ) )
    {
      ++my_progress_bar;
      continue;
    }

    std::ostringstream padding;
    padding << std::setw( 6 ) << std::setfill( '0' ) << view->id_view;

    // We have a valid view with a corresponding camera & pose
    const std::string srcImage = stlplus::create_filespec( sfm_data.s_root_path, view->s_Img_path );
    const std::string dstImage = stlplus::create_filespec( imageDirectory, "image_" + padding.str() + ".jpg" );

    Image<RGBColor>      image, image_ud, thumbnail;
    Image<unsigned char> image_mask;
    // Undistort and save the image
    if ( !ReadImage( srcImage.c_str(), &image ) )
    {
      std::cerr
          << "Unable to read the input image as a RGB image:\n"
          << srcImage << std::endl;
      ++my_progress_bar;
      continue;
    }
    Intrinsics::const_iterator iterIntrinsic = sfm_data.GetIntrinsics().find( view->id_intrinsic );
    const IntrinsicBase*       cam           = iterIntrinsic->second.get();
    if ( cam->have_disto() )
    {
      UndistortImage( image, cam, image_ud, BLACK );
      if ( !WriteImage( dstImage.c_str(), image_ud ) )
      {
        std::cerr
            << "Unable to write the output image as a RGB image:\n"
            << dstImage << std::endl;
        ++my_progress_bar;
        continue;
      }

      // Write a mask image to indicate valid pixels (because undistortion can create black pixels)
      const std::string maskImage = stlplus::create_filespec( maskDirectory, "image_" + padding.str() + ".jpg" );
      ComputeImageMask( image, cam, image_mask );
      if ( !WriteImage( maskImage.c_str(), image_mask ) )
      {
        std::cerr
            << "Unable to write the output mask image:\n"
            << maskImage << std::endl;
        ++my_progress_bar;
        continue;
      }
    }
    else // (no distortion)
    {
      // If extensions match, copy the PNG image
      if ( stlplus::extension_part( srcImage ) == "PNG" ||
           stlplus::extension_part( srcImage ) == "png" )
      {
        stlplus::file_copy( srcImage, dstImage );
      }
      else
      {
        if ( !ReadImage( srcImage.c_str(), &image ) ||
             !WriteImage( dstImage.c_str(), image ) )
        {
          std::cerr << "Unable to read and write the image" << std::endl;
          ++my_progress_bar;
          continue;
        }
      }
      ++my_progress_bar;
    }
  }
}

void export_model( const SfM_Data& sfm_data, const std::string& out_dir )
{
  const std::string output_file = stlplus::create_filespec( out_dir, "sparse_model.ply" );

  Save_PLY( sfm_data, output_file );
}

void export_project( const SfM_Data& sfm_data, const std::string& out_dir )
{
  const std::string output_file = stlplus::create_filespec( out_dir, "transforms.json" );

  const Views&           views = sfm_data.GetViews();
  system::LoggerProgress my_progress_bar( views.size(), "- Exporting cameras -" );

  std::ofstream file( output_file );

  file << "{" << file.widen( '\n' );
  file << "  \"camera_model\" : \"OPENCV\"," << file.widen( '\n' ); // or OPENCV_FISHEYE.

  file << "  \"frames\" : [" << file.widen( '\n' );

  for ( size_t i = 0; i < views.size(); ++i, ++my_progress_bar )
  {
    auto views_it = views.begin();
    std::advance( views_it, i );
    const View* view = views_it->second.get();

    if ( !sfm_data.IsPoseAndIntrinsicDefined( view ) )
    {
      continue;
    }

    std::ostringstream padding;
    padding << std::setw( 6 ) << std::setfill( '0' ) << view->id_view;

    // We have a valid view with a corresponding camera & pose
    Intrinsics::const_iterator iterIntrinsic  = sfm_data.GetIntrinsics().find( view->id_intrinsic );
    EINTRINSIC                 intrinsic_type = iterIntrinsic->second->getType();

    const IntrinsicBase*     cam         = iterIntrinsic->second.get();
    const Pinhole_Intrinsic* pinhole_cam = static_cast<const Pinhole_Intrinsic*>( cam );
    const Pose3              pose        = sfm_data.GetPoseOrDie( view );
    const Mat3               rotation    = pose.rotation();
    const openMVG::Vec3      translation = pose.translation();
    pose.center();
    const Mat3 k              = pinhole_cam->K();
    const Vec3 optical_center = pose.center();

    const std::string frame_file_path = stlplus::create_filespec( "images", "image_" + padding.str() + ".jpg" );

    file << "{" << file.widen( '\n' );
    // export intrinsics
    if ( intrinsic_type == PINHOLE_CAMERA_RADIAL1 )
    {
      std::shared_ptr<openMVG::cameras::Pinhole_Intrinsic_Radial_K1> pinhole_intrinsic_radial(
          dynamic_cast<openMVG::cameras::Pinhole_Intrinsic_Radial_K1*>( iterIntrinsic->second->clone() ) );

      file << "  \"fl_x\":" << pinhole_intrinsic_radial->focal() << "," << file.widen( '\n' );
      file << "  \"fl_y\": " << pinhole_intrinsic_radial->focal() << "," << file.widen( '\n' );
      file << "  \"cx\": " << pinhole_intrinsic_radial->principal_point().x() << "," << file.widen( '\n' );
      file << "  \"cy\": " << pinhole_intrinsic_radial->principal_point().y() << "," << file.widen( '\n' );
      file << "  \"w\": " << pinhole_cam->w() << "," << file.widen( '\n' );
      file << "  \"h\": " << pinhole_cam->h() << "," << file.widen( '\n' );
      // Since we export the undistorted image, we zero the distortion coefficients
      file << "  \"k1\": 0.0," << file.widen( '\n' );
      file << "  \"k2\": 0.0," << file.widen( '\n' );
      file << "  \"p1\": 0.0," << file.widen( '\n' );
      file << "  \"p2\": 0.0," << file.widen( '\n' );
    }
    else if ( intrinsic_type == PINHOLE_CAMERA_RADIAL3 )
    {
      std::shared_ptr<openMVG::cameras::Pinhole_Intrinsic_Radial_K3> pinhole_intrinsic_radial(
          dynamic_cast<openMVG::cameras::Pinhole_Intrinsic_Radial_K3*>( iterIntrinsic->second->clone() ) );

      file << "  \"fl_x\":" << pinhole_intrinsic_radial->focal() << "," << file.widen( '\n' );
      file << "  \"fl_y\": " << pinhole_intrinsic_radial->focal() << "," << file.widen( '\n' );
      file << "  \"cx\": " << pinhole_intrinsic_radial->principal_point().x() << "," << file.widen( '\n' );
      file << "  \"cy\": " << pinhole_intrinsic_radial->principal_point().y() << "," << file.widen( '\n' );
      file << "  \"w\": " << pinhole_cam->w() << "," << file.widen( '\n' );
      file << "  \"h\": " << pinhole_cam->h() << "," << file.widen( '\n' );
      // Since we export the undistorted image, we zero the distortion coefficients
      file << "  \"k1\": 0.0," << file.widen( '\n' );
      file << "  \"k2\": 0.0," << file.widen( '\n' );
      file << "  \"p1\": 0.0," << file.widen( '\n' );
      file << "  \"p2\": 0.0," << file.widen( '\n' );
    }
    else if ( intrinsic_type == PINHOLE_CAMERA_BROWN )
    {
      std::shared_ptr<openMVG::cameras::Pinhole_Intrinsic_Brown_T2> pinhole_intrinsic_brown( dynamic_cast<openMVG::cameras::Pinhole_Intrinsic_Brown_T2*>( iterIntrinsic->second->clone() ) );

      file << "  \"fl_x\":" << pinhole_intrinsic_brown->focal() << "," << file.widen( '\n' );
      file << "  \"fl_y\": " << pinhole_intrinsic_brown->focal() << "," << file.widen( '\n' );
      file << "  \"cx\": " << pinhole_intrinsic_brown->principal_point().x() << "," << file.widen( '\n' );
      file << "  \"cy\": " << pinhole_intrinsic_brown->principal_point().y() << "," << file.widen( '\n' );
      file << "  \"w\": " << pinhole_cam->w() << "," << file.widen( '\n' );
      file << "  \"h\": " << pinhole_cam->h() << "," << file.widen( '\n' );
      // Since we export the undistorted image, we zero the distortion coefficients
      file << "  \"k1\": 0.0," << file.widen( '\n' );
      file << "  \"k2\": 0.0," << file.widen( '\n' );
      file << "  \"p1\": 0.0," << file.widen( '\n' );
      file << "  \"p2\": 0.0," << file.widen( '\n' );
    }
    else
    {
      // standard pinhole, use the intrinsic matrix to get the focal length and principal point
      file << "  \"fl_x\":" << k( 0, 0 ) << "," << file.widen( '\n' );
      file << "  \"fl_y\": " << k( 1, 1 ) << "," << file.widen( '\n' );
      file << "  \"cx\": " << k( 0, 2 ) << "," << file.widen( '\n' );
      file << "  \"cy\": " << k( 1, 2 ) << "," << file.widen( '\n' );
      file << "  \"w\": " << pinhole_cam->w() << "," << file.widen( '\n' );
      file << "  \"h\": " << pinhole_cam->h() << "," << file.widen( '\n' );
      // Since we export the undistorted image, we zero the distortion coefficients
      file << "  \"k1\": 0.0," << file.widen( '\n' );
      file << "  \"k2\": 0.0," << file.widen( '\n' );
      file << "  \"p1\": 0.0," << file.widen( '\n' );
      file << "  \"p2\": 0.0," << file.widen( '\n' );
    }

    // export path to image
    file << "  \"file_path\":\"" << frame_file_path << "\"," << file.widen( '\n' );
    if ( cam->have_disto() )
    {
      file << "  \"mask_path\": \"" << stlplus::create_filespec( "masks", "image_" + padding.str() + ".jpg" ) << "\"" << "," << file.widen( '\n' );
    }

    // export extrinsics /!\ nerf needs a right handed frame (like OpenGL)
    file << "  \"transform_matrix\" : [" << file.widen( '\n' );

    const Mat3 inv = rotation.transpose();

    file << "    [" << inv( 0, 0 ) << ", " << -inv( 0, 1 ) << ", " << -inv( 0, 2 ) << ", " << optical_center( 0 ) << "]," << file.widen( '\n' );
    file << "    [" << inv( 2, 0 ) << ", " << -inv( 2, 1 ) << ", " << -inv( 2, 2 ) << ", " << optical_center( 2 ) << "]," << file.widen( '\n' );
    file << "    [" << -inv( 1, 0 ) << ", " << inv( 1, 1 ) << ", " << inv( 1, 2 ) << ", " << -optical_center( 1 ) << "]," << file.widen( '\n' );
    file << "    [ " << 0.0 << ", " << 0.0 << ", " << 0.0 << ", 1.0 ]" << file.widen( '\n' );

    file << " ]," << file.widen( '\n' );

    file << "  \"applied_transform\": [[1,0,0,0],[0,0,1,0],[0,-1,0,0]]" << file.widen( '\n' );
    //    file << "  \"applied_transform\":[[1,0,0,0],[0,0,-1,0],[0,1,0,0]]" << file.widen( '\n' );

    file << "}" << file.widen( '\n' );

    if ( i + 1 != views.size() )
      file << "," << file.widen( '\n' );
  }

  file << "  ]," << file.widen( '\n' );
  file << "  \"ply_file_path\":\"model/sparse_model.ply\"" << file.widen( '\n' );
  file << "}" << file.widen( '\n' );
}

/**
 * Output director structure
 *
 * out/
 * out/images           -> Undistorted images
 * out/model            -> sparse ply file.
 * out/transforms.json  -> intrinsics/extrinsics and references to the images.
 */

int main( int argc, char** argv )
{

  CmdLine     cmd;
  std::string sSfM_Data_Filename;
  std::string sOutDir = "";
  cmd.add( make_option( 'i', sSfM_Data_Filename, "sfmdata" ) );
  cmd.add( make_option( 'o', sOutDir, "outdir" ) );
  std::cout << "Note:  this program writes output in NerfStudio file format.\n";

  try
  {
    if ( argc == 1 )
      throw std::string( "Invalid command line parameter." );
    cmd.process( argc, argv );
  }
  catch ( const std::string& s )
  {
    std::cerr << "Usage: " << argv[ 0 ] << '\n'
              << "[-i|--sfmdata] filename, the SfM_Data file to convert\n"
              << "[-o|--outdir] path\n"
              << std::endl;

    std::cerr << s << std::endl;
    return EXIT_FAILURE;
  }

  // Create output dir
  if ( !stlplus::folder_exists( sOutDir ) )
    stlplus::folder_create( sOutDir );

  // Create output/images dir
  const std::string images_dir = stlplus::folder_append_separator( sOutDir ) + "images";
  if ( !stlplus::folder_exists( images_dir ) )
  {
    stlplus::folder_create( images_dir );
  }

  // Create output/masks dir
  const std::string masks_dir = stlplus::folder_append_separator( sOutDir ) + "masks";
  if ( !stlplus::folder_exists( masks_dir ) )
  {
    stlplus::folder_create( masks_dir );
  }

  // Create output/model dir
  const std::string model_dir = stlplus::folder_append_separator( sOutDir ) + "model";
  if ( !stlplus::folder_exists( model_dir ) )
  {
    stlplus::folder_create( model_dir );
  }

  // Load the SfM project file.
  std::cout << "Loading project." << std::endl;
  SfM_Data sfm_data;
  if ( !Load( sfm_data, sSfM_Data_Filename, ESfM_Data( ALL ) ) )
  {
    std::cerr << std::endl
              << "The input SfM_Data file \"" << sSfM_Data_Filename << "\" cannot be read." << std::endl;
    return EXIT_FAILURE;
  }

  // Export images.
  export_images( sfm_data, sOutDir );

  // Export model.
  export_model( sfm_data, model_dir );

  // Export cameras intrinsics/extrinsics.
  export_project( sfm_data, sOutDir );

  return EXIT_SUCCESS;
}
